### ISSUE TITLE
perf result confused

### ISSUE THREAD

**Issue by clicx** [hgst/libnvme#4]
on one nvme 4k rand write, queue=128
using spdk get about 360,000 iops;
while using libnvme got about 71,000 iops.

for read testing has no this problem.

**Comment by damien-lemoal** [comment]
Clicx,

We are behind on maintenance of libnvme (look at the last commit date. And you will see this is an understatement...). So even though libnvme will still likely work, optimization of the code and card setup updates and probably missing which result in the performance difference you are seeing.

I will try to get updates in libnvme soon. Regarding you case, what is the card you are using for your tests ? I just need a reference name (**please do not disclose on this page any information if you got the device under an NDA with the vendor**)

Best regards.

**Comment by clicx** [comment]
I have got the reason is that your perf tool not aligned to i/o size..

**Comment by damien-lemoal** [comment]
OK. I will look into this. Thank you for reporting the issue.
